import React from 'react';
import { Carrier } from './types';
import { MailIcon } from './icons';
import CarrierGrid from './CarrierGrid';

// 우편/EMS 데이터
const postCarriers: Carrier[] = [
  // 아시아
  { name: 'Korea Post (우체국)', code: 'KPOST', trackingUrl: 'https://service.epost.go.kr/trace.RetrieveRegiPrclDeliv.postal', category: 'post', region: 'Korea', isMajor: true },
  { name: 'Japan Post', code: 'JPPOST', trackingUrl: 'https://www.post.japanpost.jp/english/', category: 'post', region: 'Japan', isMajor: true },
  { name: 'China Post', code: 'CNPOST', trackingUrl: 'http://english.chinapost.com.cn/', category: 'post', region: 'China', isMajor: true },
  { name: 'Hong Kong Post', code: 'HKPOST', trackingUrl: 'https://www.hongkongpost.hk/', category: 'post', region: 'Hong Kong', isMajor: true },
  { name: 'Macau CTT', code: 'MOPOST', trackingUrl: 'https://www.ctt.gov.mo/', category: 'post', region: 'Macau' },
  { name: 'Taiwan Post', code: 'TWPOST', trackingUrl: 'https://www.post.gov.tw/', category: 'post', region: 'Taiwan', isMajor: true },
  { name: 'Singapore Post', code: 'SGPOST', trackingUrl: 'https://www.singpost.com/', category: 'post', region: 'Singapore', isMajor: true },
  { name: 'Malaysia Pos', code: 'MYPOST', trackingUrl: 'https://www.pos.com.my/', category: 'post', region: 'Malaysia' },
  { name: 'Thailand Post', code: 'THPOST', trackingUrl: 'https://www.thailandpost.co.th/', category: 'post', region: 'Thailand', isMajor: true },
  { name: 'Vietnam Post', code: 'VNPOST', trackingUrl: 'http://www.vnpost.vn/', category: 'post', region: 'Vietnam' },
  { name: 'Philippines Post', code: 'PHPOST', trackingUrl: 'https://www.phlpost.gov.ph/', category: 'post', region: 'Philippines' },
  { name: 'Indonesia Pos', code: 'IDPOST', trackingUrl: 'https://www.posindonesia.co.id/', category: 'post', region: 'Indonesia' },
  { name: 'India Post', code: 'INPOST', trackingUrl: 'https://www.indiapost.gov.in/', category: 'post', region: 'India' },
  { name: 'Pakistan Post', code: 'PKPOST', trackingUrl: 'https://www.pakpost.gov.pk/', category: 'post', region: 'Pakistan' },
  { name: 'Bangladesh Post', code: 'BDPOST', trackingUrl: 'http://www.bdpost.gov.bd/', category: 'post', region: 'Bangladesh' },
  { name: 'Sri Lanka Post', code: 'LKPOST', trackingUrl: 'https://slpost.gov.lk/', category: 'post', region: 'Sri Lanka' },
  { name: 'Nepal Post', code: 'NPPOST', trackingUrl: 'https://www.gpo.gov.np/', category: 'post', region: 'Nepal' },
  { name: 'Myanmar Post', code: 'MMPOST', trackingUrl: 'https://myanmarpost.com.mm/', category: 'post', region: 'Myanmar' },
  { name: 'Cambodia Post', code: 'KHPOST', trackingUrl: 'https://cambodiapost.com.kh/', category: 'post', region: 'Cambodia' },
  { name: 'Brunei Post', code: 'BNPOST', trackingUrl: 'http://www.post.gov.bn/', category: 'post', region: 'Brunei' },
  { name: 'Mongolia Post', code: 'MNPOST', trackingUrl: 'http://www.mongolpost.mn/', category: 'post', region: 'Mongolia' },
  { name: 'Maldives Post', code: 'MVPOST', trackingUrl: 'https://www.maldivespost.com/', category: 'post', region: 'Maldives' },
  { name: 'Bhutan Post', code: 'BTPOST', trackingUrl: 'http://www.bhutanpost.bt/', category: 'post', region: 'Bhutan' },
  // 중동
  { name: 'UAE Emirates Post', code: 'AEPOST', trackingUrl: 'https://www.emiratespost.ae/', category: 'post', region: 'UAE' },
  { name: 'Saudi Arabia SPL', code: 'SAPOST', trackingUrl: 'https://splonline.com.sa/', category: 'post', region: 'Saudi Arabia' },
  { name: 'Qatar Post', code: 'QAPOST', trackingUrl: 'https://qatarpost.qa/', category: 'post', region: 'Qatar' },
  { name: 'Kuwait Post', code: 'KWPOST', trackingUrl: 'http://moc.gov.kw/', category: 'post', region: 'Kuwait' },
  { name: 'Bahrain Post', code: 'BHPOST', trackingUrl: 'http://www.bahrainpost.gov.bh/', category: 'post', region: 'Bahrain' },
  { name: 'Oman Post', code: 'OMPOST', trackingUrl: 'https://www.omanpost.om/', category: 'post', region: 'Oman' },
  { name: 'Jordan Post', code: 'JOPOST', trackingUrl: 'https://jordanpost.com.jo/', category: 'post', region: 'Jordan' },
  { name: 'Lebanon Liban Post', code: 'LBPOST', trackingUrl: 'https://www.libanpost.com/', category: 'post', region: 'Lebanon' },
  { name: 'Israel Post', code: 'ILPOST', trackingUrl: 'https://israelpost.co.il/', category: 'post', region: 'Israel' },
  { name: 'Iran Post', code: 'IRPOST', trackingUrl: 'https://www.post.ir/', category: 'post', region: 'Iran' },
  { name: 'Iraq Post', code: 'IQPOST', trackingUrl: 'https://post.iq/en/', category: 'post', region: 'Iraq' },
  { name: 'Turkey PTT', code: 'TRPOST', trackingUrl: 'https://www.ptt.gov.tr/', category: 'post', region: 'Turkey' },
  // 유럽
  { name: 'UK Royal Mail', code: 'GBPOST', trackingUrl: 'https://www.royalmail.com/', category: 'post', region: 'UK', isMajor: true },
  { name: 'Germany Deutsche Post', code: 'DEPOST', trackingUrl: 'https://www.deutschepost.de/', category: 'post', region: 'Germany', isMajor: true },
  { name: 'France La Poste', code: 'FRPOST', trackingUrl: 'https://laposte.fr/', category: 'post', region: 'France', isMajor: true },
  { name: 'Italy Poste', code: 'ITPOST', trackingUrl: 'https://www.poste.it/', category: 'post', region: 'Italy' },
  { name: 'Spain Correos', code: 'ESPOST', trackingUrl: 'https://www.correos.es/', category: 'post', region: 'Spain' },
  { name: 'Portugal CTT', code: 'PTPOST', trackingUrl: 'https://www.ctt.pt/', category: 'post', region: 'Portugal' },
  { name: 'Netherlands PostNL', code: 'NLPOST', trackingUrl: 'https://postnl.post/', category: 'post', region: 'Netherlands' },
  { name: 'Belgium bpost', code: 'BEPOST', trackingUrl: 'https://www.bpost.be/', category: 'post', region: 'Belgium' },
  { name: 'Luxembourg Post', code: 'LUPOST', trackingUrl: 'https://www.post.lu/', category: 'post', region: 'Luxembourg' },
  { name: 'Switzerland Swiss Post', code: 'CHPOST', trackingUrl: 'https://www.post.ch/', category: 'post', region: 'Switzerland' },
  { name: 'Austria Post', code: 'ATPOST', trackingUrl: 'https://www.post.at/en/', category: 'post', region: 'Austria' },
  { name: 'Poland Poczta', code: 'PLPOST', trackingUrl: 'https://www.poczta-polska.pl/', category: 'post', region: 'Poland' },
  { name: 'Czech Česká Pošta', code: 'CZPOST', trackingUrl: 'https://www.ceskaposta.cz/', category: 'post', region: 'Czech' },
  { name: 'Slovakia Posta', code: 'SKPOST', trackingUrl: 'https://www.posta.sk/', category: 'post', region: 'Slovakia' },
  { name: 'Hungary Posta', code: 'HUPOST', trackingUrl: 'https://posta.hu/', category: 'post', region: 'Hungary' },
  { name: 'Romania Posta', code: 'ROPOST', trackingUrl: 'https://www.posta-romana.ro/', category: 'post', region: 'Romania' },
  { name: 'Bulgaria Post', code: 'BGPOST', trackingUrl: 'https://www.bgpost.bg/', category: 'post', region: 'Bulgaria' },
  { name: 'Greece ELTA', code: 'GRPOST', trackingUrl: 'https://www.elta.gr/', category: 'post', region: 'Greece' },
  { name: 'Croatia Posta', code: 'HRPOST', trackingUrl: 'https://www.posta.hr/', category: 'post', region: 'Croatia' },
  { name: 'Slovenia Pošta', code: 'SIPOST', trackingUrl: 'https://www.posta.si/', category: 'post', region: 'Slovenia' },
  { name: 'Serbia Pošta', code: 'RSPOST', trackingUrl: 'https://www.posta.rs/', category: 'post', region: 'Serbia' },
  { name: 'Bosnia Posta', code: 'BAPOST', trackingUrl: 'https://www.posta.ba/', category: 'post', region: 'Bosnia' },
  { name: 'North Macedonia Posta', code: 'MKPOST', trackingUrl: 'http://www.posta.com.mk/', category: 'post', region: 'North Macedonia' },
  { name: 'Montenegro Pošta', code: 'MEPOST', trackingUrl: 'http://postacg.me', category: 'post', region: 'Montenegro' },
  { name: 'Albania Post', code: 'ALPOST', trackingUrl: 'https://www.postashqiptare.al/', category: 'post', region: 'Albania' },
  { name: 'Ireland An Post', code: 'IEPOST', trackingUrl: 'https://www.anpost.com/', category: 'post', region: 'Ireland' },
  { name: 'Denmark PostNord', code: 'DKPOST', trackingUrl: 'https://www.postnord.dk/', category: 'post', region: 'Denmark' },
  { name: 'Sweden PostNord', code: 'SEPOST', trackingUrl: 'https://www.postnord.se/', category: 'post', region: 'Sweden' },
  { name: 'Norway Posten', code: 'NOPOST', trackingUrl: 'https://www.posten.no/', category: 'post', region: 'Norway' },
  { name: 'Finland Posti', code: 'FIPOST', trackingUrl: 'https://www.posti.fi/', category: 'post', region: 'Finland' },
  { name: 'Iceland Posturinn', code: 'ISPOST', trackingUrl: 'https://posturinn.is/', category: 'post', region: 'Iceland' },
  { name: 'Estonia Omniva', code: 'EEPOST', trackingUrl: 'https://www.omniva.ee/eng', category: 'post', region: 'Estonia' },
  { name: 'Latvia Pasts', code: 'LVPOST', trackingUrl: 'https://www.pasts.lv/', category: 'post', region: 'Latvia' },
  { name: 'Lithuania Post', code: 'LTPOST', trackingUrl: 'https://www.post.lt/', category: 'post', region: 'Lithuania' },
  { name: 'Ukraine Ukrposhta', code: 'UAPOST', trackingUrl: 'https://www.ukrposhta.ua/', category: 'post', region: 'Ukraine' },
  { name: 'Moldova Posta', code: 'MDPOST', trackingUrl: 'https://www.posta.md/', category: 'post', region: 'Moldova' },
  { name: 'Georgia Post', code: 'GEPOST', trackingUrl: 'https://www.gpost.ge/', category: 'post', region: 'Georgia' },
  { name: 'Armenia HayPost', code: 'AMPOST', trackingUrl: 'https://www.haypost.am/', category: 'post', region: 'Armenia' },
  { name: 'Azerbaijan AzerPost', code: 'AZPOST', trackingUrl: 'https://www.azerpost.az/', category: 'post', region: 'Azerbaijan' },
  { name: 'Kazakhstan Post', code: 'KZPOST', trackingUrl: 'https://post.kz/', category: 'post', region: 'Kazakhstan' },
  { name: 'Uzbekistan Pochta', code: 'UZPOST', trackingUrl: 'https://www.pochta.uz/', category: 'post', region: 'Uzbekistan' },
  { name: 'Kyrgyzstan Post', code: 'KGPOST', trackingUrl: 'https://post.kg/', category: 'post', region: 'Kyrgyzstan' },
  { name: 'Cyprus Post', code: 'CYPOST', trackingUrl: 'https://www.cypruspost.post/', category: 'post', region: 'Cyprus' },
  { name: 'Malta Post', code: 'MTPOST', trackingUrl: 'https://www.maltapost.com/', category: 'post', region: 'Malta' },
  { name: 'Jersey Post', code: 'JEPOST', trackingUrl: 'https://www.jerseypost.com/', category: 'post', region: 'Jersey' },
  { name: 'Gibraltar Post', code: 'GIPOST', trackingUrl: 'https://post.gi/', category: 'post', region: 'Gibraltar' },
  { name: 'Liechtenstein Post', code: 'LIPOST', trackingUrl: 'https://post.li/', category: 'post', region: 'Liechtenstein' },
  { name: 'San Marino Poste', code: 'SMPOST', trackingUrl: 'https://www.poste.sm/', category: 'post', region: 'San Marino' },
  { name: 'Vatican Poste', code: 'VAPOST', trackingUrl: 'https://www.postevaticane.va/en/', category: 'post', region: 'Vatican' },
  { name: 'Faroe Islands Posta', code: 'FOPOST', trackingUrl: 'https://www.posta.fo/', category: 'post', region: 'Faroe Islands' },
  { name: 'Greenland Tusass', code: 'GLPOST', trackingUrl: 'https://www.tusass.gl/', category: 'post', region: 'Greenland' },
  { name: 'Åland Post', code: 'AXPOST', trackingUrl: 'https://www.alandpost.ax/', category: 'post', region: 'Åland' },
  // 미주
  { name: 'USPS', code: 'USPOST', trackingUrl: 'https://www.usps.com/', category: 'post', region: 'USA', isMajor: true },
  { name: 'Canada Post', code: 'CAPOST', trackingUrl: 'https://www.canadapost-postescanada.ca/', category: 'post', region: 'Canada', isMajor: true },
  { name: 'Mexico Correos', code: 'MXPOST', trackingUrl: 'http://www.correosdemexico.com.mx/', category: 'post', region: 'Mexico' },
  { name: 'Brazil Correios', code: 'BRPOST', trackingUrl: 'https://www.correios.com.br/', category: 'post', region: 'Brazil' },
  { name: 'Argentina Correo', code: 'ARPOST', trackingUrl: 'https://www.correoargentino.com.ar/', category: 'post', region: 'Argentina' },
  { name: 'Chile Correos', code: 'CLPOST', trackingUrl: 'https://www.correos.cl/', category: 'post', region: 'Chile' },
  { name: 'Colombia 4-72', code: 'COPOST', trackingUrl: 'https://www.4-72.com.co/', category: 'post', region: 'Colombia' },
  { name: 'Peru SERPOST', code: 'PEPOST', trackingUrl: 'http://www.serpost.com.pe/', category: 'post', region: 'Peru' },
  { name: 'Ecuador Correos', code: 'ECPOST', trackingUrl: 'https://www.serviciopostal.gob.ec/', category: 'post', region: 'Ecuador' },
  { name: 'Bolivia Correos', code: 'BOPOST', trackingUrl: 'https://correos.gob.bo/', category: 'post', region: 'Bolivia' },
  { name: 'Paraguay Correo', code: 'PYPOST', trackingUrl: 'http://www.correoparaguayo.gov.py/', category: 'post', region: 'Paraguay' },
  { name: 'Uruguay Correo', code: 'UYPOST', trackingUrl: 'https://www.correo.com.uy/', category: 'post', region: 'Uruguay' },
  { name: 'Venezuela Ipostel', code: 'VEPOST', trackingUrl: 'http://www.ipostel.gob.ve/', category: 'post', region: 'Venezuela' },
  { name: 'Costa Rica Correos', code: 'CRPOST', trackingUrl: 'https://correos.go.cr/', category: 'post', region: 'Costa Rica' },
  { name: 'Panama Correos', code: 'PAPOST', trackingUrl: 'https://www.correospanama.gob.pa/', category: 'post', region: 'Panama' },
  { name: 'Guatemala Correos', code: 'GTPOST', trackingUrl: 'http://www.correosytelegrafos.civ.gob.gt/', category: 'post', region: 'Guatemala' },
  { name: 'Honduras Honducor', code: 'HNPOST', trackingUrl: 'http://www.honducor.gob.hn/', category: 'post', region: 'Honduras' },
  { name: 'El Salvador Correos', code: 'SVPOST', trackingUrl: 'https://www.correos.gob.sv/', category: 'post', region: 'El Salvador' },
  { name: 'Nicaragua Correos', code: 'NIPOST', trackingUrl: 'http://www.correos.gob.ni/', category: 'post', region: 'Nicaragua' },
  { name: 'Cuba Correos', code: 'CUPOST', trackingUrl: 'https://www.correos.cu/', category: 'post', region: 'Cuba' },
  { name: 'Dominican Inposdom', code: 'DOPOST', trackingUrl: 'http://inposdom.gob.do/', category: 'post', region: 'Dominican Republic' },
  { name: 'Jamaica Post', code: 'JMPOST', trackingUrl: 'https://www.jamaicapost.gov.jm/', category: 'post', region: 'Jamaica' },
  { name: 'T&T Post', code: 'TTPOST', trackingUrl: 'https://ttpost.net/', category: 'post', region: 'Trinidad and Tobago' },
  { name: 'Bahamas Postal', code: 'BSPOST', trackingUrl: 'https://www.bahamaspostal.gov.bs/', category: 'post', region: 'Bahamas' },
  { name: 'Barbados Post', code: 'BBPOST', trackingUrl: 'https://www.gov.bb/Departments/post-office', category: 'post', region: 'Barbados' },
  { name: 'Bermuda Post', code: 'BMPOST', trackingUrl: 'https://www.bermudapost.bm/', category: 'post', region: 'Bermuda' },
  { name: 'Cayman Post', code: 'KYPOST', trackingUrl: 'http://www.caymanpost.gov.ky/', category: 'post', region: 'Cayman Islands' },
  { name: 'Aruba Post', code: 'AWPOST', trackingUrl: 'https://www.postaruba.com/', category: 'post', region: 'Aruba' },
  { name: 'Curaçao Post', code: 'CWPOST', trackingUrl: 'https://www.cpostinternational.com/', category: 'post', region: 'Curaçao' },
  { name: 'Guyana Post', code: 'GYPOST', trackingUrl: 'https://guypost.gy/', category: 'post', region: 'Guyana' },
  { name: 'Suriname Surpost', code: 'SRPOST', trackingUrl: 'https://www.surpost.com/', category: 'post', region: 'Suriname' },
  // 오세아니아
  { name: 'Australia Post', code: 'AUPOST', trackingUrl: 'https://auspost.com.au/', category: 'post', region: 'Australia', isMajor: true },
  { name: 'New Zealand Post', code: 'NZPOST', trackingUrl: 'https://www.nzpost.co.nz/', category: 'post', region: 'New Zealand' },
  { name: 'Fiji Post', code: 'FJPOST', trackingUrl: 'https://www.postfiji.com.fj/', category: 'post', region: 'Fiji' },
  { name: 'Samoa Post', code: 'WSPOST', trackingUrl: 'https://www.samoapost.ws/', category: 'post', region: 'Samoa' },
  { name: 'Tonga Post', code: 'TOPOST', trackingUrl: 'http://tongapost.to/', category: 'post', region: 'Tonga' },
  { name: 'Vanuatu Post', code: 'VUPOST', trackingUrl: 'https://www.vanuatupost.vu/', category: 'post', region: 'Vanuatu' },
  { name: 'Solomon Post', code: 'SBPOST', trackingUrl: 'https://www.solomonpost.com.sb/', category: 'post', region: 'Solomon Islands' },
  { name: 'Nauru Post', code: 'NRPOST', trackingUrl: 'https://www.naurupost.nr/', category: 'post', region: 'Nauru' },
  { name: 'New Caledonia OPT', code: 'NCPOST', trackingUrl: 'https://www.opt.nc/courrier', category: 'post', region: 'New Caledonia' },
  { name: 'French Polynesia', code: 'PFPOST', trackingUrl: 'https://www.farerata.pf/', category: 'post', region: 'French Polynesia' },
  // 아프리카
  { name: 'South Africa Post', code: 'ZAPOST', trackingUrl: 'https://www.postoffice.co.za/', category: 'post', region: 'South Africa' },
  { name: 'Egypt Post', code: 'EGPOST', trackingUrl: 'https://www.egyptpost.org/', category: 'post', region: 'Egypt' },
  { name: 'Morocco Poste', code: 'MAPOST', trackingUrl: 'https://www.poste.ma/', category: 'post', region: 'Morocco' },
  { name: 'Tunisia Poste', code: 'TNPOST', trackingUrl: 'http://www.poste.tn/', category: 'post', region: 'Tunisia' },
  { name: 'Algeria Post', code: 'DZPOST', trackingUrl: 'https://www.poste.dz/', category: 'post', region: 'Algeria' },
  { name: 'Ethiopia Post', code: 'ETPOST', trackingUrl: 'https://ethio.post/', category: 'post', region: 'Ethiopia' },
  { name: 'Kenya Post', code: 'KEPOST', trackingUrl: 'https://www.posta.co.ke/', category: 'post', region: 'Kenya' },
  { name: 'Tanzania Post', code: 'TZPOST', trackingUrl: 'https://www.posta.co.tz/', category: 'post', region: 'Tanzania' },
  { name: 'Uganda Post', code: 'UGPOST', trackingUrl: 'https://www.ugapost.co.ug/', category: 'post', region: 'Uganda' },
  { name: 'Ghana Post', code: 'GHPOST', trackingUrl: 'https://ghanapost.com.gh/', category: 'post', region: 'Ghana' },
  { name: 'Senegal La Poste', code: 'SNPOST', trackingUrl: 'https://www.laposte.sn/', category: 'post', region: 'Senegal' },
  { name: 'Côte d\'Ivoire Post', code: 'CIPOST', trackingUrl: 'https://laposte.ci.post/', category: 'post', region: 'Ivory Coast' },
  { name: 'Cameroon Campost', code: 'CMPOST', trackingUrl: 'http://www.campost.cm/', category: 'post', region: 'Cameroon' },
  { name: 'Mauritius Post', code: 'MUPOST', trackingUrl: 'https://www.mauritiuspost.mu/', category: 'post', region: 'Mauritius' },
  { name: 'Seychelles Post', code: 'SCPOST', trackingUrl: 'https://www.seychelles-post.com/', category: 'post', region: 'Seychelles' },
  { name: 'Rwanda I-Posita', code: 'RWPOST', trackingUrl: 'http://i-posita.rw/', category: 'post', region: 'Rwanda' },
  { name: 'Botswana Post', code: 'BWPOST', trackingUrl: 'https://botswanapost.post/', category: 'post', region: 'Botswana' },
  { name: 'Namibia Nampost', code: 'NAPOST', trackingUrl: 'https://www.nampost.com.na/', category: 'post', region: 'Namibia' },
  { name: 'Zimbabwe Post', code: 'ZWPOST', trackingUrl: 'https://www.zimpost.co.zw/', category: 'post', region: 'Zimbabwe' },
  { name: 'Zambia Post', code: 'ZMPOST', trackingUrl: 'http://www.zampost.com.zm/', category: 'post', region: 'Zambia' },
  { name: 'Angola Correios', code: 'AOPOST', trackingUrl: 'https://www.correiosdeangola.ao/', category: 'post', region: 'Angola' },
  { name: 'Mozambique Correios', code: 'MZPOST', trackingUrl: 'http://www.correios.co.mz/', category: 'post', region: 'Mozambique' },
  { name: 'Eswatini Post', code: 'SZPOST', trackingUrl: 'http://www.eswatinipost.co.sz/', category: 'post', region: 'Eswatini' },
  { name: 'Cabo Verde Correios', code: 'CVPOST', trackingUrl: 'https://correios.cv/', category: 'post', region: 'Cabo Verde' },
  { name: 'Benin La Poste', code: 'BJPOST', trackingUrl: 'https://laposte.bj/', category: 'post', region: 'Benin' },
  { name: 'Togo La Poste', code: 'TGPOST', trackingUrl: 'https://www.laposte.tg/', category: 'post', region: 'Togo' },
  { name: 'Burkina Faso La Poste', code: 'BFPOST', trackingUrl: 'https://laposte.bf/', category: 'post', region: 'Burkina Faso' },
  { name: 'Mali La Poste', code: 'MLPOST', trackingUrl: 'https://laposte.ml/', category: 'post', region: 'Mali' },
  { name: 'Madagascar Paositra', code: 'MGPOST', trackingUrl: 'https://paositramalagasy.mg/', category: 'post', region: 'Madagascar' },
  { name: 'Libya Post', code: 'LYPOST', trackingUrl: 'https://libyapost.ly/', category: 'post', region: 'Libya' },
  { name: 'Sudan Sudapost', code: 'SDPOST', trackingUrl: 'http://sudapost.sd/', category: 'post', region: 'Sudan' },
  { name: 'Djibouti La Poste', code: 'DJPOST', trackingUrl: 'https://www.laposte.dj/', category: 'post', region: 'Djibouti' },
  { name: 'Mauritania Mauripost', code: 'MRPOST', trackingUrl: 'http://www.mauripost.post/', category: 'post', region: 'Mauritania' },
  { name: 'Burundi Poste', code: 'BIPOST', trackingUrl: 'http://www.poste.bi/', category: 'post', region: 'Burundi' },
  { name: 'Sierra Leone Salpost', code: 'SLPOST', trackingUrl: 'https://salpost.gov.sl/', category: 'post', region: 'Sierra Leone' },
  { name: 'Liberia Post', code: 'LRPOST', trackingUrl: 'https://mopt.gov.lr/', category: 'post', region: 'Liberia' },
  // 추가 누락분
  { name: 'Afghanistan Post', code: 'AFPOST', trackingUrl: 'https://afghanpost.gov.af/en', category: 'post', region: 'Afghanistan' },
  { name: 'Palestine Post', code: 'PSPOST', trackingUrl: 'https://www.palpost.ps/', category: 'post', region: 'Palestine' },
  { name: 'Anguilla Post', code: 'AIPOST', trackingUrl: 'http://www.aps.ai/', category: 'post', region: 'Anguilla' },
  { name: 'Belize Post', code: 'BZPOST', trackingUrl: 'http://www.belizepostalservice.gov.bz', category: 'post', region: 'Belize' },
  { name: 'Grenada Post', code: 'GDPOST', trackingUrl: 'http://www.grenadapostal.com/', category: 'post', region: 'Grenada' },
  { name: 'Saint Kitts Post', code: 'KNPOST', trackingUrl: 'https://post.kn/', category: 'post', region: 'Saint Kitts' },
  { name: 'Saint Lucia Post', code: 'LCPOST', trackingUrl: 'http://www.stluciapostal.com/', category: 'post', region: 'Saint Lucia' },
  { name: 'Tuvalu Post', code: 'TVPOST', trackingUrl: 'http://www.tuvalupost.tv/', category: 'post', region: 'Tuvalu' },
  { name: 'Kiribati Post', code: 'KIPOST', trackingUrl: 'https://www.mict.gov.ki/postal', category: 'post', region: 'Kiribati' },
  { name: 'Bonaire Post', code: 'BQPOST', trackingUrl: 'http://www.fxdc-post.com/', category: 'post', region: 'Bonaire' },
];

interface TrackerPostProps {
  adSlot?: React.ReactNode;
}

const TrackerPost: React.FC<TrackerPostProps> = ({ adSlot }) => {
  return (
    <CarrierGrid
      carriers={postCarriers}
      title="우편/EMS"
      subtitle={`전세계 ${postCarriers.length}개+ 우정사업본부 추적`}
      icon={<MailIcon className="w-5 h-5 text-white" />}
      iconBgClass="bg-gradient-to-br from-rose-500 to-rose-600"
      adSlot={adSlot}
    />
  );
};

export default TrackerPost;
export { postCarriers };
